"""I did something

Revision ID: d8a380459790
Revises: 
Create Date: 2024-07-21 11:44:06.481450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a380459790'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.Text(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
